/* Canonical book list (Catholic canon, POC Malayalam names). Used for ordering,
 * the upload dialog's book selector and reference parsing ("ഉത്പ 3:15", "gen 3:15"). */
window.BOOK_CATALOG = [
  ['GEN', 'ഉത്പത്തി', 'Genesis', 50, 'ഉല്പത്തി ഉൽപ്പത്തി ഉത്പ ഉല്പ'],
  ['EXO', 'പുറപ്പാട്', 'Exodus', 40, 'പുറ'],
  ['LEV', 'ലേവ്യർ', 'Leviticus', 27, 'ലേവ്യ'],
  ['NUM', 'സംഖ്യ', 'Numbers', 36, ''],
  ['DEU', 'നിയമാവർത്തനം', 'Deuteronomy', 34, 'നിയ'],
  ['JOS', 'ജോഷ്വ', 'Joshua', 24, 'ജോഷ്വാ'],
  ['JDG', 'ന്യായാധിപന്മാർ', 'Judges', 21, 'ന്യായ'],
  ['RUT', 'റൂത്ത്', 'Ruth', 4, ''],
  ['1SA', '1 സാമുവൽ', '1 Samuel', 31, '1സാമു'],
  ['2SA', '2 സാമുവൽ', '2 Samuel', 24, '2സാമു'],
  ['1KI', '1 രാജാക്കന്മാർ', '1 Kings', 22, '1രാജ'],
  ['2KI', '2 രാജാക്കന്മാർ', '2 Kings', 25, '2രാജ'],
  ['1CH', '1 ദിനവൃത്താന്തം', '1 Chronicles', 29, '1ദിന'],
  ['2CH', '2 ദിനവൃത്താന്തം', '2 Chronicles', 36, '2ദിന'],
  ['EZR', 'എസ്രാ', 'Ezra', 10, ''],
  ['NEH', 'നെഹെമിയാ', 'Nehemiah', 13, ''],
  ['TOB', 'തോബിത്', 'Tobit', 14, ''],
  ['JDT', 'യൂദിത്', 'Judith', 16, ''],
  ['EST', 'എസ്തേർ', 'Esther', 10, ''],
  ['1MA', '1 മക്കബായർ', '1 Maccabees', 16, ''],
  ['2MA', '2 മക്കബായർ', '2 Maccabees', 15, ''],
  ['JOB', 'ജോബ്', 'Job', 42, ''],
  ['PSA', 'സങ്കീർത്തനങ്ങൾ', 'Psalms', 150, 'സങ്കീ സങ്കീർത്തനം'],
  ['PRO', 'സുഭാഷിതങ്ങൾ', 'Proverbs', 31, 'സുഭാ'],
  ['ECC', 'സഭാപ്രസംഗകൻ', 'Ecclesiastes', 12, ''],
  ['SNG', 'ഉത്തമഗീതം', 'Song of Songs', 8, ''],
  ['WIS', 'ജ്ഞാനം', 'Wisdom', 19, ''],
  ['SIR', 'പ്രഭാഷകൻ', 'Sirach', 51, ''],
  ['ISA', 'ഏശയ്യാ', 'Isaiah', 66, 'ഏശ'],
  ['JER', 'ജറെമിയാ', 'Jeremiah', 52, 'ജറെ'],
  ['LAM', 'വിലാപങ്ങൾ', 'Lamentations', 5, ''],
  ['BAR', 'ബാറൂക്ക്', 'Baruch', 6, ''],
  ['EZK', 'എസെക്കിയേൽ', 'Ezekiel', 48, ''],
  ['DAN', 'ദാനിയേൽ', 'Daniel', 14, ''],
  ['HOS', 'ഹോസിയാ', 'Hosea', 14, ''],
  ['JOL', 'ജോയേൽ', 'Joel', 3, ''],
  ['AMO', 'ആമോസ്', 'Amos', 9, ''],
  ['OBA', 'ഒബാദിയാ', 'Obadiah', 1, ''],
  ['JON', 'യോനാ', 'Jonah', 4, ''],
  ['MIC', 'മിക്കാ', 'Micah', 7, ''],
  ['NAM', 'നാഹും', 'Nahum', 3, ''],
  ['HAB', 'ഹബക്കുക്ക്', 'Habakkuk', 3, ''],
  ['ZEP', 'സെഫാനിയാ', 'Zephaniah', 3, ''],
  ['HAG', 'ഹഗ്ഗായി', 'Haggai', 2, ''],
  ['ZEC', 'സഖറിയാ', 'Zechariah', 14, ''],
  ['MAL', 'മലാക്കി', 'Malachi', 4, ''],
  ['MAT', 'മത്തായി', 'Matthew', 28, ''],
  ['MRK', 'മർക്കോസ്', 'Mark', 16, ''],
  ['LUK', 'ലൂക്കാ', 'Luke', 24, ''],
  ['JHN', 'യോഹന്നാൻ', 'John', 21, ''],
  ['ACT', 'അപ്പസ്തോലപ്രവർത്തനങ്ങൾ', 'Acts', 28, 'അപ്പ'],
  ['ROM', 'റോമാ', 'Romans', 16, ''],
  ['1CO', '1 കോറിന്തോസ്', '1 Corinthians', 16, ''],
  ['2CO', '2 കോറിന്തോസ്', '2 Corinthians', 13, ''],
  ['GAL', 'ഗലാത്തിയാ', 'Galatians', 6, ''],
  ['EPH', 'എഫേസോസ്', 'Ephesians', 6, ''],
  ['PHP', 'ഫിലിപ്പി', 'Philippians', 4, ''],
  ['COL', 'കൊളോസോസ്', 'Colossians', 4, ''],
  ['1TH', '1 തെസലോനിക്കാ', '1 Thessalonians', 5, ''],
  ['2TH', '2 തെസലോനിക്കാ', '2 Thessalonians', 3, ''],
  ['1TI', '1 തിമോത്തേയോസ്', '1 Timothy', 6, ''],
  ['2TI', '2 തിമോത്തേയോസ്', '2 Timothy', 4, ''],
  ['TIT', 'തീത്തോസ്', 'Titus', 3, ''],
  ['PHM', 'ഫിലെമോൻ', 'Philemon', 1, ''],
  ['HEB', 'ഹെബ്രായർ', 'Hebrews', 13, ''],
  ['JAS', 'യാക്കോബ്', 'James', 5, ''],
  ['1PE', '1 പത്രോസ്', '1 Peter', 5, ''],
  ['2PE', '2 പത്രോസ്', '2 Peter', 3, ''],
  ['1JN', '1 യോഹന്നാൻ', '1 John', 5, ''],
  ['2JN', '2 യോഹന്നാൻ', '2 John', 1, ''],
  ['3JN', '3 യോഹന്നാൻ', '3 John', 1, ''],
  ['JUD', 'യൂദാസ്', 'Jude', 1, ''],
  ['REV', 'വെളിപാട്', 'Revelation', 22, ''],
].map(([id, name, en, chapters, alias], i) => ({
  id, name, en, chapters, order: i, testament: i < 46 ? 'OT' : 'NT',
  aliases: alias ? alias.split(' ') : [],
}));
