// Builds app/js/ai-data.js — the AI translation bundled with the app — from one JSON file per chapter:
//   node tools/build-ai-data.js <folder with GEN_1.json, GEN_2.json, …> [model] [GEN,MAT,…]
// The optional list keeps books that are still being translated out of the bundle.
// Each file: { "book": "GEN", "chapter": 1, "verses": [{ "v": 1, "heading": "", "text": "…" }, …] }
// (the shape functions/api/translate.js asks Claude for). The reader shows these chapters in the AI view
// when Firestore has no AI translation of its own for them (one made later with the app's button wins).
const fs = require('fs');
const path = require('path');

const dir = process.argv[2];
const model = process.argv[3] || 'claude-opus-5-5';
const only = process.argv[4] ? new Set(process.argv[4].split(',')) : null;
if (!dir) { console.error('usage: node tools/build-ai-data.js <folder> [model]'); process.exit(2); }

// same item format as the reader's text and functions/api/translate.js: { h } heading, { v, t, p } verse
function toItems(verses) {
  const items = [];
  verses.forEach((x, i) => {
    const h = String(x.heading || '').trim();
    if (h) items.push({ h });
    const it = { v: x.v, t: String(x.text).trim() };
    if (h || i === 0) it.p = 1;
    items.push(it);
  });
  return items;
}

const books = {};
let chapters = 0, verses = 0;
const files = fs.readdirSync(dir).filter((f) => /^[1-4]?[A-Z]{2,3}_\d+\.json$/.test(f) && (!only || only.has(f.split('_')[0])));
for (const f of files) {
  const d = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8'));
  const vs = d.verses || [];
  const bad = vs.findIndex((x, i) => x.v !== i + 1 || typeof x.text !== 'string' || !x.text.trim());
  if (!vs.length || bad >= 0) { console.error(`${f}: verse ${bad + 1} missing or out of order — not built`); process.exit(1); }
  (books[d.book] = books[d.book] || {})[d.chapter] = toItems(vs);
  chapters++; verses += vs.length;
}
if (!chapters) { console.error('no chapter files in ' + dir); process.exit(1); }

// one chapter per line, so a diff shows which chapters changed
const lines = [];
for (const [b, chs] of Object.entries(books)) {
  const nums = Object.keys(chs).map(Number).sort((x, y) => x - y);
  lines.push(`  ${JSON.stringify(b)}: {\n` + nums.map((n) => `    "${n}": ${JSON.stringify(chs[n])}`).join(',\n') + '\n  }');
}
const out = `/* Generated by tools/build-ai-data.js — the AI translation (Claude, from the Hebrew / Greek original),
 * shown in the reader's AI view. Loaded only when that view or ☰ → AI പരിഭാഷകൾ is opened. */
window.AI_BIBLE = { "version": ${JSON.stringify(new Date().toISOString().slice(0, 10))}, "model": ${JSON.stringify(model)}, "books": {
${lines.join(',\n')}
} };
`;
const target = path.join(__dirname, '..', 'app', 'js', 'ai-data.js');
fs.writeFileSync(target, out);
console.log(`${path.relative(process.cwd(), target)}: ${chapters} chapters, ${verses} verses, ${(Buffer.byteLength(out) / 1024).toFixed(0)} KB`);
