#!/usr/bin/env node
/*
 * Converts the chapter PDFs into app/js/data.js (the bundled Bible text).
 *
 *   node tools/build-data.js [pdfFolder] [--book-id GEN] [--book-name ഉത്പത്തി]
 *
 * Uses the same extractor + parser the browser uses for uploads, so a PDF
 * uploaded in the app gives the same result as one converted here.
 * Chapters typed from a printed Bible (no PDF) are kept in the in-app editor
 * format as tools/sources/<BOOK ID>/<chapter>.txt and are added as well.
 * Requires Node 18+.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const PdfExtract = require('../app/js/pdf-extract.js');
const P = require('../app/js/parser.js');
const FIXES = require('./text-fixes.js');

const args = process.argv.slice(2);
const opt = (name, def) => { const i = args.indexOf(name); return i >= 0 ? args.splice(i, 2)[1] : def; };
const bookId = opt('--book-id', 'GEN');
const bookName = opt('--book-name', 'ഉത്പത്തി');
const folder = path.resolve(args[0] || path.join(__dirname, '..'));
const outFile = path.join(__dirname, '..', 'app', 'js', 'data.js');

(async () => {
  const files = fs.readdirSync(folder).filter((f) => /\.pdf$/i.test(f));
  const chapters = {};
  const report = [];
  // pass 1: extract everything and build a word list (used to re-join words split by line breaks)
  const extracted = [];
  const lexicon = new Map();
  for (const f of files) {
    const { pages } = await PdfExtract.extract(fs.readFileSync(path.join(folder, f)));
    extracted.push({ f, pages });
    pages.flat().forEach((p) => P.addToLexicon(lexicon, P.normalize(p.text)));
  }
  // pass 2: parse
  for (const { f, pages } of extracted) {
    const hint = P.chapterFromFilename(f);
    const res = P.parsePdfParagraphs(pages, { chapter: hint, bookNames: [bookName], lexicon });
    for (const ch of res.chapters) {
      const n = ch.chapter || hint;
      if (!n) { report.push(`${f}: chapter number not found — skipped`); continue; }
      if (hint && n !== hint) report.push(`${f}: header says chapter ${n}, filename says ${hint} — using ${n}`);
      const fixes = (FIXES[bookId] || {})[n] || [];
      let items = ch.items;
      if (fixes.length) {
        let text = P.toEditorText(items);
        for (const [find, repl] of fixes) {
          const count = text.split(find).length - 1;
          if (count !== 1) { report.push(`ch ${String(n).padStart(2)}: fix not applied (found ${count}×): ${find}`); continue; }
          text = text.replace(find, () => repl);
        }
        items = P.parseEditorText(text);
      }
      chapters[n] = items;
      const vs = P.verseMap(items);
      const heads = items.filter((x) => x.h).map((x) => x.h);
      const warnings = P.validate(items);
      report.push(`ch ${String(n).padStart(2)}: ${String(vs.size).padStart(2)} verses (max ${Math.max(0, ...vs.keys())})` +
        (fixes.length ? ` | ${fixes.length} fixes` : '') +
        (heads.length ? ` | headings: ${heads.join(' / ')}` : '') +
        (warnings.length ? ` | ${warnings.join('; ')}` : ''));
    }
  }
  const sorted = {};
  Object.keys(chapters).map(Number).sort((a, b) => a - b).forEach((k) => { sorted[k] = chapters[k]; });
  const data = {
    version: new Date().toISOString().slice(0, 10),
    books: [{ id: bookId, name: bookName, chapters: sorted }].concat(textBooks(report)),
  };
  fs.writeFileSync(outFile,
    '/* Generated by tools/build-data.js — edits made in the app can be exported to replace this file. */\n' +
    'window.BIBLE_DATA = ' + JSON.stringify(data) + ';\n');
  report.sort((a, b) => (parseInt(a.slice(3)) || 0) - (parseInt(b.slice(3)) || 0));
  console.log(report.join('\n'));
  console.log(`\nWrote ${Object.keys(sorted).length} chapters → ${path.relative(process.cwd(), outFile)} (${(fs.statSync(outFile).size / 1024).toFixed(0)} KB)`);
})().catch((e) => { console.error(e); process.exit(1); });

// books typed in the editor format: tools/sources/<BOOK ID>/<chapter>.txt, in canon order
function textBooks(report) {
  const dir = path.join(__dirname, 'sources');
  if (!fs.existsSync(dir)) return [];
  const ctx = { window: {} };
  vm.runInNewContext(fs.readFileSync(path.join(__dirname, '..', 'app', 'js', 'books.js'), 'utf8'), ctx);
  const catalog = new Map(ctx.window.BOOK_CATALOG.map((b) => [b.id, b]));
  return fs.readdirSync(dir)
    .filter((id) => id !== bookId && catalog.has(id))
    .sort((a, b) => catalog.get(a).order - catalog.get(b).order)
    .map((id) => {
      const chapters = {};
      fs.readdirSync(path.join(dir, id)).map((f) => parseInt(f, 10)).filter((n) => n > 0).sort((a, b) => a - b)
        .forEach((n) => {
          const items = P.parseEditorText(fs.readFileSync(path.join(dir, id, n + '.txt'), 'utf8'));
          const warnings = P.validate(items);
          chapters[n] = items;
          report.push(`${id} ${n}: ${P.verseMap(items).size} verses (typed text)` + (warnings.length ? ` | ${warnings.join('; ')}` : ''));
        });
      return { id, name: catalog.get(id).name, chapters };
    });
}
