#!/usr/bin/env node
/*
 * Converts the chapter PDFs into app/js/data.js (the bundled Bible text).
 *
 *   node tools/build-data.js [pdfFolder] [--book-id GEN] [--book-name ഉത്പത്തി]
 *
 * Uses the same extractor + parser the browser uses for uploads, so a PDF
 * uploaded in the app gives the same result as one converted here.
 * Other books are kept in tools/sources/<BOOK ID>/: chapter PDFs (chapter number
 * in the file name, e.g. "അധ്യായം 3.pdf") and chapters typed from a printed Bible
 * in the in-app editor format (<chapter>.txt). They are added as well.
 * Requires Node 18+.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const PdfExtract = require('../app/js/pdf-extract.js');
const P = require('../app/js/parser.js');
const FIXES = require('./text-fixes.js');

const args = process.argv.slice(2);
const opt = (name, def) => { const i = args.indexOf(name); return i >= 0 ? args.splice(i, 2)[1] : def; };
const bookId = opt('--book-id', 'GEN');
const bookName = opt('--book-name', 'ഉത്പത്തി');
const folder = path.resolve(args[0] || path.join(__dirname, '..'));
const outFile = path.join(__dirname, '..', 'app', 'js', 'data.js');

(async () => {
  const report = [];
  const sorted = await pdfChapters(folder, bookId, bookName, report);
  const data = {
    version: new Date().toISOString().slice(0, 10),
    books: [{ id: bookId, name: bookName, chapters: sorted }].concat(await sourceBooks(report)),
  };
  fs.writeFileSync(outFile,
    '/* Generated by tools/build-data.js — edits made in the app can be exported to replace this file. */\n' +
    'window.BIBLE_DATA = ' + JSON.stringify(data) + ';\n');
  // group by book (main book first), then chapter
  const key = (s) => { const m = s.match(/^(?:([A-Z0-9]{3})|ch) +(\d+)/); return m ? [m[1] || '', +m[2]] : ['', 0]; };
  report.sort((a, b) => { const [ba, na] = key(a), [bb, nb] = key(b); return ba === bb ? na - nb : ba < bb ? -1 : 1; });
  console.log(report.join('\n'));
  console.log(`\nWrote ${Object.keys(sorted).length} chapters → ${path.relative(process.cwd(), outFile)} (${(fs.statSync(outFile).size / 1024).toFixed(0)} KB)`);
})().catch((e) => { console.error(e); process.exit(1); });

// the chapter PDFs in a folder → { chapter: items } in chapter order; `prefix` (the book id)
// marks the report lines of books other than the main one
async function pdfChapters(folder, bookId, bookName, report, prefix = '') {
  const files = fs.readdirSync(folder).filter((f) => /\.pdf$/i.test(f));
  const chapters = {};
  // pass 1: extract everything and build a word list (used to re-join words split by line breaks)
  const extracted = [];
  const lexicon = new Map();
  for (const f of files) {
    const { pages } = await PdfExtract.extract(fs.readFileSync(path.join(folder, f)));
    extracted.push({ f, pages });
    pages.flat().forEach((p) => P.addToLexicon(lexicon, P.normalize(p.text)));
  }
  // pass 2: parse
  for (const { f, pages } of extracted) {
    const hint = P.chapterFromFilename(f);
    const res = P.parsePdfParagraphs(pages, { chapter: hint, bookNames: [bookName], lexicon });
    if (!res.chapters.length) report.push(`${prefix}${f}: no text found — skipped`);
    for (const ch of res.chapters) {
      const n = ch.chapter || hint;
      if (!n) { report.push(`${prefix}${f}: chapter number not found — skipped`); continue; }
      if (hint && n !== hint) report.push(`${prefix}${f}: header says chapter ${n}, filename says ${hint} — using ${n}`);
      const fixes = (FIXES[bookId] || {})[n] || [];
      let items = ch.items;
      if (fixes.length) {
        let text = P.toEditorText(items);
        for (const [find, repl] of fixes) {
          const count = text.split(find).length - 1;
          if (count !== 1) { report.push(`${prefix || 'ch '}${String(n).padStart(2)}: fix not applied (found ${count}×): ${find}`); continue; }
          text = text.replace(find, () => repl);
        }
        items = P.parseEditorText(text);
      }
      chapters[n] = items;
      const vs = P.verseMap(items);
      const heads = items.filter((x) => x.h).map((x) => x.h);
      const warnings = P.validate(items);
      report.push(`${prefix || 'ch '}${String(n).padStart(2)}: ${String(vs.size).padStart(2)} verses (max ${Math.max(0, ...vs.keys())})` +
        (fixes.length ? ` | ${fixes.length} fixes` : '') +
        (heads.length ? ` | headings: ${heads.join(' / ')}` : '') +
        (warnings.length ? ` | ${warnings.join('; ')}` : ''));
    }
  }
  const sorted = {};
  Object.keys(chapters).map(Number).sort((a, b) => a - b).forEach((k) => { sorted[k] = chapters[k]; });
  return sorted;
}

// the books in tools/sources/<BOOK ID>/, in canon order: chapter PDFs, and chapters typed in the
// editor format (<chapter>.txt — a typed chapter replaces a PDF of the same chapter)
async function sourceBooks(report) {
  const dir = path.join(__dirname, 'sources');
  if (!fs.existsSync(dir)) return [];
  const ctx = { window: {} };
  vm.runInNewContext(fs.readFileSync(path.join(__dirname, '..', 'app', 'js', 'books.js'), 'utf8'), ctx);
  const catalog = new Map(ctx.window.BOOK_CATALOG.map((b) => [b.id, b]));
  const ids = fs.readdirSync(dir)
    .filter((id) => id !== bookId && catalog.has(id))
    .sort((a, b) => catalog.get(a).order - catalog.get(b).order);
  const books = [];
  for (const id of ids) {
    const chapters = await pdfChapters(path.join(dir, id), id, catalog.get(id).name, report, id + ' ');
    fs.readdirSync(path.join(dir, id)).filter((f) => /^\d+\.txt$/.test(f)).map((f) => parseInt(f, 10))
      .forEach((n) => {
        const items = P.parseEditorText(fs.readFileSync(path.join(dir, id, n + '.txt'), 'utf8'));
        const warnings = P.validate(items);
        chapters[n] = items;
        report.push(`${id} ${n}: ${P.verseMap(items).size} verses (typed text)` + (warnings.length ? ` | ${warnings.join('; ')}` : ''));
      });
    const sorted = {};
    Object.keys(chapters).map(Number).sort((a, b) => a - b).forEach((k) => { sorted[k] = chapters[k]; });
    books.push({ id, name: catalog.get(id).name, chapters: sorted });
  }
  return books;
}
